<a href="https://colab.research.google.com/github/ShankarDhandapani/Google-colab/blob/master/Pandas_and_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <h1 align=center>Pandas</h2>
<hr>

In [0]:
#@title Importing Packages
import pandas as pd

In [0]:
course = ['MSc','MCA','MTech','PhD']
rno = [216, 205, 300, 400]
d = list(zip(course,rno))
df = pd.DataFrame(data = d ,columns = ['course','rollno'])
df

course  rollno
0    MSc     216
1    MCA     205
2  MTech     300
3    PhD     400

In [0]:
#@title Export to CSV
df.to_csv('course.csv',index=False,header=False)

In [0]:
#@title Reading CSV
f = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/labs/top_selling_albums.csv"
df = pd.read_csv(f)
df

Artist                            Album  Released   Length  \
0  Michael Jackson                         Thriller      1982  0:42:19   
1            AC/DC                    Back in Black      1980  0:42:11   
2       Pink Floyd        The Dark Side of the Moon      1973  0:42:49   
3  Whitney Houston                    The Bodyguard      1992  0:57:44   
4        Meat Loaf                  Bat Out of Hell      1977  0:46:33   
5           Eagles  Their Greatest Hits (1971-1975)      1976  0:43:08   
6         Bee Gees             Saturday Night Fever      1977  1:15:54   
7    Fleetwood Mac                          Rumours      1977  0:40:01   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   
5   rock, soft rock, folk rock                              32.2   
6                        disco                              20.6   
7                    soft rock                              27.9   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65  30-Nov-82        NaN    10.0  
1                        50  25-Jul-80        NaN     9.5  
2                        45  01-Mar-73        NaN     9.0  
3                        44  17-Nov-92          Y     8.5  
4                        43  21-Oct-77        NaN     8.0  
5                        42  17-Feb-76        NaN     7.5  
6                        40  15-Nov-77          Y     7.0  
7                        40  04-Feb-77        NaN     6.5

In [0]:
df.head()

Artist                      Album  Released   Length  \
0  Michael Jackson                   Thriller      1982  0:42:19   
1            AC/DC              Back in Black      1980  0:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  0:42:49   
3  Whitney Houston              The Bodyguard      1992  0:57:44   
4        Meat Loaf            Bat Out of Hell      1977  0:46:33   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65  30-Nov-82        NaN    10.0  
1                        50  25-Jul-80        NaN     9.5  
2                        45  01-Mar-73        NaN     9.0  
3                        44  17-Nov-92          Y     8.5  
4                        43  21-Oct-77        NaN     8.0

In [0]:
df.tail(2)

Artist                 Album  Released   Length      Genre  \
6       Bee Gees  Saturday Night Fever      1977  1:15:54      disco   
7  Fleetwood Mac               Rumours      1977  0:40:01  soft rock   

   Music Recording Sales (millions)  Claimed Sales (millions) Released.1  \
6                              20.6                        40  15-Nov-77   
7                              27.9                        40  04-Feb-77   

  Soundtrack  Rating  
6          Y     7.0  
7        NaN     6.5

<h2 align=center> Viewing Data and Accessing Data </h2>

In [0]:
a = df[['Artist','Rating']]
a

Artist  Rating
0  Michael Jackson    10.0
1            AC/DC     9.5
2       Pink Floyd     9.0
3  Whitney Houston     8.5
4        Meat Loaf     8.0
5           Eagles     7.5
6         Bee Gees     7.0
7    Fleetwood Mac     6.5

In [0]:
a.iloc[1,0] # 1st Row, 0th Column

'AC/DC'

In [0]:
a.loc[6,'Artist'] # 6th Row in Artist Column

'Bee Gees'

<h2 align=center> Properties of Dataset </h2>

In [0]:
#@title Shape (rows and columns)
df.shape

(8, 10)

In [0]:
#@title Datatypes
df.dtypes

Artist                               object
Album                                object
Released                              int64
Length                               object
Genre                                object
Music Recording Sales (millions)    float64
Claimed Sales (millions)              int64
Released.1                           object
Soundtrack                           object
Rating                              float64
dtype: object

In [0]:
#@title Statistics Properties
df.describe()

Released  Music Recording Sales (millions)  \
count     8.000000                          8.000000   
mean   1979.250000                         28.125000   
std       5.800246                          8.189322   
min    1973.000000                         20.600000   
25%    1976.750000                         23.300000   
50%    1977.000000                         26.750000   
75%    1980.500000                         28.975000   
max    1992.000000                         46.000000   

       Claimed Sales (millions)     Rating  
count                  8.000000   8.000000  
mean                  46.125000   8.250000  
std                    8.271077   1.224745  
min                   40.000000   6.500000  
25%                   41.500000   7.375000  
50%                   43.500000   8.250000  
75%                   46.250000   9.125000  
max                   65.000000  10.000000

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
Artist                              8 non-null object
Album                               8 non-null object
Released                            8 non-null int64
Length                              8 non-null object
Genre                               8 non-null object
Music Recording Sales (millions)    8 non-null float64
Claimed Sales (millions)            8 non-null int64
Released.1                          8 non-null object
Soundtrack                          2 non-null object
Rating                              8 non-null float64
dtypes: float64(2), int64(2), object(6)
memory usage: 720.0+ bytes


In [0]:
#@title Unique Values of Columns
df['Artist'].unique()

array(['Michael Jackson', 'AC/DC', 'Pink Floyd', 'Whitney Houston',
       'Meat Loaf', 'Eagles', 'Bee Gees', 'Fleetwood Mac'], dtype=object)

In [0]:
#@title Size of Dataset (Row * Column )
df.size 

80

# <h1 align=center>Numpy</h2>
<hr>

In [0]:
#@title Importing Package
import numpy as np 

In [0]:
a=[[11,12,13],[21,22,23],[31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [0]:
#@title Converting List into Numpy
b = np.array(a)
b

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [0]:
print(b.size)
print(b.ndim)

9
2


In [0]:
#@title Accessing Elements of Array
b[0,1]

12

In [0]:
a = 2 * b

In [0]:
c = a + b
c

array([[33, 36, 39],
       [63, 66, 69],
       [93, 96, 99]])

In [0]:
d = a * b
d

array([[ 242,  288,  338],
       [ 882,  968, 1058],
       [1922, 2048, 2178]])

In [0]:
#@title We use the numpy function dot to multiply the arrays together
e = np.dot(a,b) 
e

array([[1552, 1624, 1696],
       [2812, 2944, 3076],
       [4072, 4264, 4456]])

In [0]:
e.T

array([[1552, 2812, 4072],
       [1624, 2944, 4264],
       [1696, 3076, 4456]])

<h2 align = "center"> Numpy Operations </h2>

In [0]:
#@title Zeros and Ones
a = np.zeros((3,4)) # zeros(row,column)
print(a)
b = np.ones((2,2)) # once(row,column)
print("\n",b)
c = np.empty((3,2))
print("\n",c) # output may vary

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 1.]
 [1. 1.]]

 [[2. 0.]
 [2. 0.]
 [6. 0.]]


In [0]:
#@title arange
np.arange(0,2,0.2) # (start,end,dif)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [0]:
#@title linspace
a = np.linspace(0,1,10) # 10 numbers from 0 to 1
b = np.linspace(2, 3, num=5, endpoint = False) # without endpoint 3
c = np.linspace(2, 3, num=5, endpoint = True) # with endpoint 3
print(a,"\n",b,"\n",c)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ] 
 [2.  2.2 2.4 2.6 2.8] 
 [2.   2.25 2.5  2.75 3.  ]


In [0]:
#@title random
np.random.random_sample((5,2))

array([[0.11915737, 0.80086056],
       [0.24484907, 0.59638308],
       [0.26242566, 0.47001179],
       [0.44384806, 0.23260107],
       [0.78831673, 0.32703952]])

In [0]:
#@title sum,min,max
print(a.sum())
print(a.min())
print(a.max())

5.0
0.0
1.0


# <h1 align=center>Exercise</h2>
<p>1. Do pandas operations for this dataset https://www.kaggle.com/kaggle/kaggle-survey-2018.</p>
<p>2. Generate 1oK Randoms numbers for <b>A</b>  and 10K numbers inbetween 1K to 8K for <b> B</b> and calulate matrix addition and stored that result in CSV file. </p>
<hr>